---
title: "Group s01"
author: "Kyle Gilde"
date: "April 13, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=10, 
                      fig.height=5,
                      fig.align = 'center', 
                      echo = F,
                      cache = TRUE)
```

```{r}
install_and_load_pkgs <- function(pkg){
  # Load a vector of packages and install them if needed.
  # CODE SOURCE: https://gist.github.com/stevenworthington/3178163
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) install.packages(new.pkg, dependencies = T)
  sapply(pkg, require, character.only = T, quietly = T, warn.conflicts = T)
}

# list the packages here
pkgs <- c("dplyr", "tidyr", "forecast", "ggplot2", "xts", "doMC", "kableExtra", "openxlsx", "readxl", "gridExtra")

install_and_load_pkgs(pkgs)

# if you are using windows, use this command:
# install.packages("doMC", repos="http://R-Forge.R-project.org")
```




```{r data}
# read file
raw_df <- 
  readxl::read_excel('c:/Users/kyleg/data624_hw_group_2/Project1/Reference/Set for Class.xls', col_names = TRUE) 

group_s01_df <- 
  raw_df %>% 
  dplyr::filter(group == "S01") %>% 
  dplyr::select(SeriesInd, Var01, Var02) %>% 
  arrange(SeriesInd)

# filter to S01 and vars 1 and 2
train_s01_df <- 
  group_s01_df %>%  
  dplyr::filter(SeriesInd < 43022)


nrow(train_s01_df)
s01_var01_ts <- ts(train_s01_df$Var01)
na_indices <- which(is.na(s01_var01_ts))
s01_var01_ts_int <- na.interp(s01_var01_ts)
s01_var02_ts <- ts(train_s01_df$Var02)



```


```{r}




sapply(train_s01_df, function(x) sum(is.na(x)))


gridExtra::grid.arrange(
  autoplot(s01_var01_ts_int),
  autoplot(s01_var02_ts),
  ggAcf(s01_var01_ts_int),
  ggAcf(s01_var02_ts),
  nrow=2,
  ncol=2
)

ggAcf(s01_var01_ts, lag.max = 500)
ggAcf(s01_var02_ts, lag.max = 500)


s01_var02_ts_freq <- ts(train_s01_df$Var02, frequency = findfrequency(s01_var02_ts))
decompose(s01_var02_ts_freq) %>% autoplot()
findfrequency(s01_var01_ts)



checkresiduals(s01_var01_ts)

train_s01_df$SeriesInd

```

```{r}


fets <- function(x, h) {
  forecast(ets(x), h = h)
}

farima <- function(x, h) {
  forecast(auto.arima(x, stepwise = F, approximation = F), h=h)
}

arima_errors <- tsCV(s01_var01_ts_int, farima, h = 140)
ets_errors <- tsCV(s01_var01_ts_int, fets, h = 140)

head(arima_errors)
head(ets_errors)
accuracy(a1, s01_var01_ts_int)[, c("MAPE", "MASE")]
accuracy(a1)
s01_var01_ts_int 
s01_var02_ts  
save(a1, file = "at.RData")
```



``` {r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}

```